services:
  # Web Service (Django)
  - type: web
    name: django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"

  # Celery Worker
  - type: worker
    name: celery-worker
    env: python
    buildCommand: "./build.sh"
    startCommand: "celery -A myproject worker --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings.production
      - key: SECRET_KEY
        sync: false

  # Celery Beat (Optional - for scheduled tasks)
  - type: worker
    name: celery-beat
    env: python
    buildCommand: "./build.sh"
    startCommand: "celery -A myproject beat --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings.production
      - key: SECRET_KEY
        sync: false

databases:
  - name: postgres-db
    databaseName: myproject_db
    user: myproject_user

services:
  - type: redis
    name: redis-cache
    ipAllowList: []
